---
title: "Count detected _P. capsici_ genes"
author: "R. Stam"
date: "6 November 2014"
output: html_document
---

Short script to calculate the number of genes that have reads assigned to them in out P capsici-tomato data
Data comes from FeatureCounts run on data mapped with STAR.

Count number of genes with reads mapped to them
------------------------------

Read data, merge data, 


```{r}
setwd("/Volumes/rstam/141001_FC_with_effectors/")

###

myFiles = list.files(path="/Volumes/rstam/141001_FC_with_effectors/", pattern="t.txt$")

data <- lapply(myFiles, read.table, sep="\t", header = TRUE)
merged.data.frame = Reduce(function(...) merge(..., all=T), data)
rownames(merged.data.frame) <- as.vector(merged.data.frame[,1])
dataf <- merged.data.frame[,7:61]

names <- c("c00_14","c16_14","c24_14","c04_14","c08_14",
           "inf00_14","inf16_14","inf24_14","inf04_14","inf08_14",
           "c00_22","c16_22","c24_22","c04_22","c08_22",
           "inf00_22","inf16_22","inf24_22","inf04_22","inf08_22",
           "c00_24","c16_24","c24_24","c04_24","c08_24",
           "inf00_24","inf16_24","inf24_24","inf04_24","inf08_24",
           "c00_28","c16_28","c24_28","c04_28","c08_28",
           "inf00_28","inf16_28","inf24_28","inf04_28","inf08_28",
           "inf00_31","inf16_31","inf24_31","inf04_31","inf08_31",
           "c00_31","c16_31","c24_31","c04_31","c08_31",
           "gc_a","gc_h","gc_i","gc_j","myc") 
colnames(dataf) <- names
datao <- dataf[,c(1,11,21,31,46,4,14,24,34,49,5,15,25,35,50,2,12,22,32,47,3,13,23,33,48,
                                           6,16,26,36,41,9,19,29,39,44,10,20,30,40,45,7,17,27,37,42,8,18,28,38,43,
                                           51,52,53,54,55)]
```

Count all genes with 1, 3 or 5 reads, make table and graphs
```{r plot, warning=FALSE}
x <- list(1:5, 6:10, 11:15, 16:20, 21:25, 26:30, 31:35, 36:40, 41:45, 46:50, 51:55)
names2 <- c("c00","c04","c08","c16","c24","inf00","inf04","inf08","inf16","inf24","in vitro")
## All genes with >1 read
count <- as.data.frame(t(colSums(datao != 0)))
means <- do.call(cbind, lapply(x, function(i) rowMeans(count[, i])))
## All genes with >3 reads
count3 <- as.data.frame(t(colSums(datao > 3)))
means3 <- do.call(cbind, lapply(x, function(i) rowMeans(count3[, i])))
## All genes with >5 reads
count5 <- as.data.frame(t(colSums(datao > 5)))
means5 <- do.call(cbind, lapply(x, function(i) rowMeans(count5[, i])))


counts <- as.matrix(rbind(means,means3,means5))
colnames(counts) <- names2
rownames(counts) <- c("1read", "3reads", "5reads")


sterr <- function(x) sd(x, na.rm = TRUE)/sqrt(length(x))
sterrs1 <- do.call(cbind, lapply(x, function(i) sterr(count[i])))
sterrs3 <- do.call(cbind, lapply(x, function(i) sterr(count3[i])))
sterrs5 <- do.call(cbind, lapply(x, function(i) sterr(count5[i])))

par(mfrow=c(1,3))

bary <- barplot(counts[1,], ylab = "# of genes", xaxt = "n", space=1, ylim = c(0,15000), main = "genes with reads")
labels <- paste(colnames(counts))
text(c(2,4,6,8,10,12,14,16,18,20,22)-0.5, par("usr")[3] - 0.25, srt = 45, adj = 1,
     labels = labels[1:10], xpd = TRUE)
arrows(bary ,counts[1,]+sterrs1, bary, counts[1,], angle=90, code=1, length = 0.05)
arrows(bary ,counts[1,]-sterrs1, bary, counts[1,], angle=90, code=1, length = 0.05)
######
bary <- barplot(counts[2,], ylab = "# of genes", xaxt = "n", space=1, ylim = c(0,15000), main = "genes with >3 reads")
labels <- paste(colnames(counts))
text(c(2,4,6,8,10,12,14,16,18,20,22)-0.5, par("usr")[3] - 0.25, srt = 45, adj = 1,
     labels = labels[1:10], xpd = TRUE)
arrows(bary ,counts[2,]+sterrs3, bary, counts[2,], angle=90, code=1, length = 0.05)
arrows(bary ,counts[2,]-sterrs3, bary, counts[2,], angle=90, code=1, length = 0.05)
#######
bary <- barplot(counts[3,], ylab = "# of genes", xaxt = "n", space=1, ylim = c(0,15000), main = "genes with >5 reads")
labels <- paste(colnames(counts))
text(c(2,4,6,8,10,12,14,16,18,20,22)-0.5, par("usr")[3] - 0.25, srt = 45, adj = 1,
     labels = labels[1:10], xpd = TRUE)
arrows(bary ,counts[3,]+sterrs5, bary, counts[3,], angle=90, code=1, length = 0.05)
arrows(bary ,counts[3,]-sterrs5, bary, counts[3,], angle=90, code=1, length = 0.05)
```
